buildpoc: Test new output/error management

diff --git a/.docker/build/linux/Dockerfile b/.docker/build/linux/Dockerfile
--- a/.docker/build/linux/Dockerfile
+++ b/.docker/build/linux/Dockerfile
@@ -11,7 +11,9 @@ RUN rm -rf  ${MYHOME}/FStar/.git
 WORKDIR ${MYHOME}/FStar
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
 
-RUN make -C src -j ${MAXTHREADS} utest-prelude >> ${BUILDLOGFILE} && echo "success" > "result.txt" || echo "failed" > "result.txt"
+# For anything printed on stdout or stderr, gather everything and
+# get everything printed to both the log file and stderr
+RUN { make -C src -j ${MAXTHREADS} utest-prelude && echo "success" > "result.txt" || echo "failed" > "result.txt" ; } 2>&1 | tee --append ${BUILDLOGFILE} >&2
 
 RUN echo $(date -u '+%Y-%m-%d %H:%M:%S') >> ${BUILDLOGFILE}
 
